name = "faction-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "faction-db"
database_id = "a588145b-ccfb-44bb-b574-d9c1f30efee5"

[[kv_namespaces]]
binding = "TOKENS"
id = "f3f8ca7f910c4ba8ac6e0c0c06a637da"
